apiVersion: v2
kubeVersion: ">= 1.26.0"
name: portal-shell
description: Helm Chart for the portal-shell frontend application
type: application
version: 1.3.0
appVersion: "1.3.0"
icon: https://avatars.githubusercontent.com/u/55493511?s=200&v=4
